GET http://localhost:7295/api/SimpleFunction?name=Vanch

###
POST http://localhost:7295/api/SimpleFunction

{
    "name": "Visual Studio"
}

















###
POST {{apiurl}}/api/SimpleFunction
x-functions-key: {{SimpleFunctionKey}}
Content-Type: application/json

{
    "name": ""
}
